#!/usr/bin/env bash

if [[ ! -x "$(which docker)" ]]; then
    echo 'Please, install docker!'
    exit 1
fi

if [[ ! -x "$(which curl)" ]]; then
    echo 'Please, install curl!'
    exit 1
fi

if [[ ! "$(id -u)" -eq "0" ]]; then
    echo 'Please, run me as root!'
    exit 1
fi

docker pull "ejzspb/sockd"
cid=$(docker run -d -p 127.0.0.1:1080:1080 "ejzspb/sockd")
if [[ ! "$cid" ]]; then
    echo 'Could not start container!'
    exit 1
fi
ip=$(curl --proxy-user sockd:sockd --socks5 127.0.0.1:1080 'http://ejz.ru/ip' 2>/dev/null)
docker stop "$cid"
docker rmi -f "ejzspb/sockd"

if [[ $(echo "$ip" | sed -ne '/^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+$/p') ]]; then
    echo 'TEST - OK!'
    exit 0
else
    echo 'TEST - FAILED!'
    exit 1
fi
